### ISSUE TITLE
提示问题

### ISSUE THREAD

**Issue by tudoukp** [aliyun-UED/aliyun-sdk-js#10]
使用 oss.putObject 的时候老是提示  [TypeError: Not a buffer]   ，最后发现是 配置名字secretAccessKey写错了，莫名其妙的提示

**Comment by bugknightyyp** [comment]
我也遇到同样问题了，本来accessKeyId accessKeySecret形式上一样的，官网也是这么叫的，又发明一个secretAccessKey

**Comment by calidion** [comment]
代码质量比较差，又是要逼我自己写的节奏。
