### ISSUE TITLE
dayu方法调用报错Insufficient isv permissions

### ISSUE THREAD

**Issue by lileltp** [aliyun-UED/aliyun-sdk-js#109]
{ error_response: 
   { code: 11,
     msg: 'Insufficient isv permissions',
     sub_code: 'isv.permission-api-package-limit',
     sub_msg: 'scope ids is 11022 11600 11863',
     request_id: 'iv0aea4gb8jq' } }

**Comment by chylvina** [comment]
你调用错了，问问大鱼技术支持
