### ISSUE TITLE
更新MTS

### ISSUE THREAD

**Issue by aa403210842** [aliyun-UED/aliyun-sdk-js#111]
视乎mst有新版本

想用一些新查询API：如
[查询媒体-使用OSS文件地址](https://help.aliyun.com/document_detail/44460.html?spm=5176.doc44459.6.649.RmpG7Z)

**Comment by chylvina** [comment]
应该已经更新了，有问题再回复谢谢。

**Comment by aa403210842** [comment]
mts-2014-06-18.json 中没有 QueryMediaList，QueryMediaListByURL， UpdateMediaPublishState
等接口
https://help.aliyun.com/document_detail/44463.html?spm=5176.doc44458.6.652.K0rHi9
