### ISSUE TITLE
支持v3版开放搜索API相关计划

### ISSUE THREAD

**Issue by rankun203** [aliyun-UED/aliyun-sdk-js#119]
现在支持的是开放搜索v2版，向阿里云请求会直接失败，返回的像2030这样的错误码在阿里云文档中都找不到原因。

**Comment by goto100** [comment]
开放搜索暂时没有开发 v3 sdk 的计划；

2030 错误码是 "当前应用类型不支持此 URI"，你大概是调用了标准版专有 api 了吧。

**Comment by rankun203** [comment]
@goto100 正解，谢谢。

我们已经切换到开放搜索高级版。客服那边反馈说：

> 高级版近期不会取消对v2 api的支持，但是以后的方向肯定是只有一个版本的api，即全部都使用基于实现v3版的api或对应的sdk来访问对应的应用。  

所以我们还是有点担心会不会出现阿里云直接屏蔽v2 SDK访问高级版的功能，如果届时我们无法用上v3的SDK，问题就大了。
