### ISSUE TITLE
在阿里云开通了短信服务，使用ALY.DAYU没法发送短信，返回权限错误

### ISSUE THREAD

**Issue by beesui** [aliyun-UED/aliyun-sdk-js#127]
{ error_response:
   { code: 11,
     msg: 'Insufficient isv permissions',
     sub_code: 'isv.permission-api-package-limit',
     sub_msg: 'scope ids is xxx xxxxx xxxx',
     request_id: 'xxxxxxx' } }

**Comment by wurui** [comment]
我刚准备提个issue也是ALY.DAYU的问题，语音用不了。
短信服务我没用这个sdk代码，看这个文档https://market.aliyun.com/products/57002003/cmapi011900.html#item-1，采用appCode调用http://sms.market.alicloudapi.com/singleSendSms这个接口是能走通的。

**Comment by chylvina** [comment]
请使用官网提供的发送短信 sdk
https://help.aliyun.com/document_detail/57458.html?spm=a2c4g.11186623.6.571.Cmdnzs
