### ISSUE TITLE
阿里云开通了语音服务，用ALY.DAYU调用报错，InvalidVersion

### ISSUE THREAD

**Issue by wurui** [aliyun-UED/aliyun-sdk-js#129]
<?xml version='1.0' encoding='UTF-8'?><Error><RequestId>14418598-7719-4731-91DF-4385338D3F56</RequestId><HostId>dyvmsapi.aliyuncs.com</HostId><Code>InvalidVersion</Code><Message>Specified parameter Version is not valid.</Message></Error>
其实是报JSON解析错误，因为就是返回的XML，调试进去才看到的。
提过工单，未解决，只得在此提issue了，望指条明路。
附上代码：
var ALY = require("aliyun-sdk")

var Dayu = new ALY.DAYU({
    accessKeyId: 'LTA******',
    secretAccessKey: 'A2VEE********',
    endpoint: 'http://dyvmsapi.aliyuncs.com',
    apiVersion: '2015-12-16',
    region:'cn-hangzhou'
});
Dayu.singlecall({
        'tts_param':{
            name:'车主',
            reason:'测试测试'
        },
        'called_num':'181****',
        'called_show_num':'057156215***',
        'tts_code':'TTS_74815***'
    },
    function(err, data) {
        if (err) {
            console.log('Error:~', err);
            console.log('Data:~', data);
            return;
        }

    });

**Comment by chylvina** [comment]
你好，这个问题我周末找时间解决一下，抱歉久等了。

**Comment by wurui** [comment]
是否解决了？

**Comment by wurui** [comment]
请问有人在解决吗？我的月租放那都扣了两个月的钱的，一条语言服务没用过？到底能不能用吗？

**Comment by chylvina** [comment]
你好，语音服务之前是没有接入到 aliyun sdk 的，所以你无法调用成功，现在接入了。1.10.12 版本
```javascript
new DYVMSAPI
...
```

**Comment by wurui** [comment]
OK
