### ISSUE TITLE
sdk 不支持 stream 么？

### ISSUE THREAD

**Issue by berwin** [aliyun-UED/aliyun-sdk-js#13]
伪代码如下：

```javascript
    var busboy = new Busboy({ headers: req.headers });
    busboy.on('file', function(fieldname, file, filename, encoding, mimetype) {
        file.pipe( oss ); //  用stream的形式直接上传
    });
    req.pipe(busboy);
```

这样的话，用户上传一个比较大的文件，也能够直接pipe到oss上了~~

请问现在支持这种使用方法吗？

@xiong-liang

**Comment by chylvina** [comment]
hi，可以实现的，请参考 aws s3 的一个组件，https://github.com/nathanpeck/s3-upload-stream
也欢迎你能做一个类似的组件并开源出来。

**Comment by berwin** [comment]
呵！呵！

**Comment by berwin** [comment]
明白了，谢谢袄~~

**Comment by berwin** [comment]
https://github.com/berwin/aliyun-oss-upload-stream 实现了一个使用stream的方式上传文件的Nodejs模块~目前是1.0.0版本

**Comment by berwin** [comment]
https://github.com/berwin/aliyun-oss-upload-stream 实现了一个类似的组件，目前是1.0.0版本~

**Comment by chylvina** [comment]
非常感谢! 我放在首页上。

**Comment by berwin** [comment]
好~谢谢啊~ 如果发现什么bug或者缺少的功能及时通知我，我会及时更新和发布新版本~~

**Comment by chylvina** [comment]
好的 :+1:
