### ISSUE TITLE
cs-2015-12-15.json parse error

### ISSUE THREAD

**Issue by everyun** [aliyun-UED/aliyun-sdk-js#133]
downloaded from npm.taobao.org

file: aliyun-sdk/apis/cs-2015-12-15.json
line 146

**Comment by tonyljl526** [comment]
i met the same problem just now

**Comment by luin** [comment]
Same issue here. Seems this issue was introduced in version 1.10.10.

**Comment by chylvina** [comment]
fixed, sorry for the mistake.
