### ISSUE TITLE
Aliyun SLS 相关的信息需要更新了

### ISSUE THREAD

**Issue by iugo** [aliyun-UED/aliyun-sdk-js#139]
1. Aliyun SLS 已经改名, 不再叫 SLS 了. 日志服务（Log Service，简称 Log）
2. SLS API手册 链接已经失效.

**Comment by chylvina** [comment]
谢谢反馈，是这样的，但是为了保证向前兼容，我们还是叫做 SLS

**Comment by iugo** [comment]
@chylvina 
SLS 的文档链接还是会跳到:
https://help.aliyun.com/index.html

**Comment by iugo** [comment]
文档链接已经更新, 可以跳转了.
