### ISSUE TITLE
vod js sdk上传文件出错 - 

### ISSUE THREAD

**Issue by derekzuo-github** [aliyun-UED/aliyun-sdk-js#149]
js引用：
<script src="/js/aliyun/aliyun-sdk.min.js"></script>
<script src="/js/aliyun/vod-sdk-upload-1.0.6.min.js"></script>

通过VODUpload上传视频到oss，分块上传的最后一步，返回异常：
The XML you provided was not well-formed or did not validate against our published schema.

尝试换成了1.0.7，问题依然存在； 能否看下如何解决？

**Comment by derekzuo-github** [comment]
错误code为：MalformedXML，查看请求参数为：

<CompleteMultipartUpload>
<Part>
<PartNumber>1</PartNumber>
</Part>
</CompleteMultipartUpload>

从文档看是缺少了Etag节点？ 为什么会丢失Etag节点呢？

**Comment by derekzuo-github** [comment]
<CompleteMultipartUpload><Part><PartNumber>1</PartNumber></Part></CompleteMultipartUpload>

**Comment by derekzuo-github** [comment]
`<CompleteMultipartUpload><Part><PartNumber>1</PartNumber></Part></CompleteMultipartUpload>`

**Comment by derekzuo-github** [comment]
@daxingplay @xiong-liang    请帮忙看看，感谢！

**Comment by derekzuo-github** [comment]
解决了：在跨域请求配置中添加暴露Etag；功能有点儿隐蔽

**Comment by chylvina** [comment]
赞
