### ISSUE TITLE
删除某个文件夹下唯一文件，该文件夹也没了？

### ISSUE THREAD

**Issue by Luncher** [aliyun-UED/aliyun-sdk-js#15]
譬如说：
文件路径： /aaa/bbb/ccc.txt
该路径下除了ccc.txt没有其他文件。即：aaa下只有bbb，bbb下只有ccc.txt文件。
**如果我现在把ccc.txt**删除了，那么整个路径/aaa/bbb/ccc.txt都没了。= =||
*设计如此？*

**Comment by chylvina** [comment]
是的，设计如此。

发自我的 iPhone
