### ISSUE TITLE
listObjects Delimiter 参数填写'/'提示非法

### ISSUE THREAD

**Issue by Luncher** [aliyun-UED/aliyun-sdk-js#16]
早上更新了下SDK，发现之前的代码不能跑了，listObjects Delimiter 参数填写'/'提示非法.

**Comment by Luncher** [comment]
我把版本回退就OK了，估计是参数校验出错了吧！
ps：为啥没有做自动化测试呢？

**Comment by chylvina** [comment]
已经发布 1.5.1 修复此问题，感谢你的反馈。目前我没有时间做全面的自动化测试，欢迎帮忙呵呵。

**Comment by Luncher** [comment]
我很乐意呀！这个模块代码写的很巧妙，我得多花时间来研究～

**Comment by chylvina** [comment]
好的欢迎

发自我的 iPhone
