### ISSUE TITLE
SDK not working on Function Compute

### ISSUE THREAD

**Issue by roura356a** [aliyun-UED/aliyun-sdk-js#170]
When I clone this project locally and run it with node6, it works. But running it on Function Compute doesn't.

All I'm trying is to use the ECS service and use 'StopInstance'. It just times out. My code is:

```
const ALY = require('aliyun-sdk')

const accessKeyId = '_accessKeyId_'
const secretAccessKey = '_secretAccessKey_'

exports.handler = (event, context, callback) => {
    const args = JSON.parse(event)

    const ecs = new ALY.ECS({
        accessKeyId,
        secretAccessKey,
        endpoint: 'https://ecs.aliyuncs.com',
        apiVersion: '2014-05-26',
    })

    ecs.stopInstance(args, callback)
}
```

I tried with node4.4, node6 & node8. Function Compute uses `aliyun-sdk@1.10.12`

**Comment by roura356a** [comment]
Looks like the ECS API is outdated in this project. The current version requires `SecurityToken` when used in *Function Compute* as it uses roles.

When I don't supply that parameter it says `Unexpected key 'SecurityToken' found in params`.

But when I supply it says `The input parameter "SecurityToken" that is mandatory for processing this request is not supplied`

**Comment by JuanManuelRinconCarrera** [comment]
Do you find the solution?
