### ISSUE TITLE
希望添加TypeScript支持，并提交到npm。

### ISSUE THREAD

**Issue by itsuki-hayashi** [aliyun-UED/aliyun-sdk-js#25]
如题……

**Comment by phoue** [comment]
+1

**Comment by chylvina** [comment]
TypeScript 我不太了解，具体需要做什么？

**Comment by phoue** [comment]
我也用不到TypeScript，只想能提交到npm，用起来方便。另外浏览器上传文件的时候，手机浏览器如UC,上传失败。还没查出怎么回事。目测是FileReader 的onload事件。

**Comment by edsgerlin** [comment]
@chylvina 其实就是添加类型标注。阿里的代码太乱了我也不知道怎么加QAQ

**Comment by Roman-Lo** [comment]
要是可以支持npm的话那是最好不过的！

**Comment by Manweill** [comment]
或者直接使用typescript编写~

**Comment by jamesliauw** [comment]
就是增加index.d.ts TypeScript语法识别文件，这个可有办法提供?

**Comment by JayenLee** [comment]
typescript声明是否有加入进来？

**Comment by ZanMinKian** [comment]
ts已经很流行，建议用ts重写。
