### ISSUE TITLE
求ONS的SDK

### ISSUE THREAD

**Issue by AKIo0O** [aliyun-UED/aliyun-sdk-js#29]
现在跑的nsq。希望官方早点出啊。

之前说9月份出：[链接](https://github.com/aliyun-UED/aliyun-sdk-js/issues/20)

**Comment by chylvina** [comment]
hi，抱歉我看了 ONS 的实现，发现和其他阿里云产品不同，Nodejs 的 SDK 只能要求 ONS 团队自己出了。你可以发工单要求此功能。谢谢。
