### ISSUE TITLE
multipartUpload的例子能不能改进下

### ISSUE THREAD

**Issue by meteormatt** [aliyun-UED/aliyun-sdk-js#34]
https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/samples/oss/multipartUpload.js#L16
这行在上传大于内存的文件时, 会报错.
```bash
buffer.js:71
    throw new RangeError('Attempt to allocate Buffer larger than maximum ' +
          ^
RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
```
![qq20151014-0 2x](https://cloud.githubusercontent.com/assets/424475/10482600/ddb1abba-72ab-11e5-86d8-c6f7b75c5d2f.png)

**Comment by joeylin** [comment]
我觉得，可以使用stream, 读取到一定的buffer 之后，再上传，边读边上传，这样的话就不会出现那个问题了。

**Comment by meteormatt** [comment]
@joeylin 是的. 但是官方的SDK没有支持`stream`上传. 即使`putObject`方法也一样, 只能用`buffer`.

**Comment by chylvina** [comment]
https://github.com/meteormatt/oss-upload-stream

**Comment by meteormatt** [comment]
这个属于自己挖了个坑往里跳吗 :grimacing:

**Comment by joeylin** [comment]
哈哈，我本来也写了一份，发现你这个更优雅，就没有传上来了。
