### ISSUE TITLE
华为手机使用putObject时，status code永远回0。

### ISSUE THREAD

**Issue by noway55m** [aliyun-UED/aliyun-sdk-js#35]
华为手机使用putObject时，status code永远回0，而且没有错误丢出。
测试时确定图片已经上传(因为可以取得刚上传的图片)，经过抓包后服务器有回复200，所以定位应该是sdk的问题。
sdk代码发生在：if (xhr.status === 0) return 0;

**Comment by phoue** [comment]
同时华为手机，遇到同样的问题。但查阅了各种资料后，初步认识是：手机浏览器（webkit 内核的）并没有完全实现XMLHttpRequest的全部特性，比如progress等，readystatechange事件里，xhr.status的值一直为0,可能也是因为这个。
