### ISSUE TITLE
按照 https://github.com/meteormatt/oss-upload-stream怎么实现MD5的文件完整性校验

### ISSUE THREAD

**Issue by numone123** [aliyun-UED/aliyun-sdk-js#39]
按照 https://github.com/meteormatt/oss-upload-stream实现上传，
怎么实现MD5的文件完整性校验，也就是传到oss里面的文件的完整性问题，
谢谢！

**Comment by chylvina** [comment]
这个是自动完成的，不需要设置。关于md5完整完整性，可以查查资料。
