### ISSUE TITLE
deleteObjects出错

### ISSUE THREAD

**Issue by mehwww** [aliyun-UED/aliyun-sdk-js#4]
在我自己的程序以及samples里删除多个Objects都会报“MissingArgument: Missing Some Required Arguments”的错，单个删除的话倒是没问题

另外源代码里的调试的代码段能不能用[debug](https://github.com/visionmedia/debug)管理一下，现在是只要有DEBUG的值就会输出调试信息，开发起来有点不方便，如果可以的话我可以帮忙修改

**Comment by chylvina** [comment]
欢迎帮忙，不过 debug 会增加 sdk 的模块依赖，最好使用简单的代码实现功能。删除多个 Objects 报错的问题我看一下，谢谢！

**Comment by chylvina** [comment]
发布 v1.1.1 版本，bug 解决了，感谢你的反馈！
