### ISSUE TITLE
oss的putObject怎么用?.好像没找到详细的例子和api

### ISSUE THREAD

**Issue by guqiyao** [aliyun-UED/aliyun-sdk-js#41]
oss的putObject怎么用?.好像没找到详细的例子和api

**Comment by chylvina** [comment]
https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/samples/oss/PutObject.js

**Comment by guqiyao** [comment]
你好,按照例子报了putObject is not a function这个错
我遍历了oss这个对象,确实没发现这个方法

**Comment by guqiyao** [comment]
原来需要加上"apiVersion"这个配置才会有..

**Comment by cesiya23** [comment]
请问 putObject 方法能够在浏览器应用中使用吗？还是必须在node服务器环境下使用？
