### ISSUE TITLE
SignatureDoesNotMatch

### ISSUE THREAD

**Issue by leovs** [aliyun-UED/aliyun-sdk-js#44]
error: { [SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.]
  message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  headers: 
   { server: 'AliyunOSS',
     date: 'Tue, 15 Dec 2015 04:45:53 GMT',
     'content-type': 'application/xml',
     'content-length': '1027',
     connection: 'close',
     'x-oss-request-id': '566F9B013A7B8CC20D7424DB',
     'x-oss-server-side-encryption': 'AES256' },
  time: Tue Dec 15 2015 12:45:51 GMT+0800 (中国标准时间),
  statusCode: 403,
  retryable: false }

**Comment by chylvina** [comment]
提供一下调用代码

**Comment by leovs** [comment]
var ALY = require('aliyun-sdk');

var oss = new ALY.OSS({
    "accessKeyId": "***",
    "secretAccessKey": "****",
    "endpoint": 'http://oss-cn-hangzhou.aliyuncs.com',
    "apiVersion": '2013-10-15'
});
var fs = require('fs');

fs.readFile('C:/Users/Administrator/Desktop/test.sql', function (err, data) {
    if (err) {
        console.log('error:', err);
        return;
    }
    oss.putObject({
            Bucket: 'test4lvs',
            Key: 'test.sql',
            Body: data,
            AccessControlAllowOrigin: '',
            ContentType: 'text/plain',
            CacheControl: 'no-cache',
            ContentDisposition: '',
            ContentEncoding: 'utf-8',
            ServerSideEncryption: 'AES256',
            Expires: null
        },
        function (err, data) {
            if (err) {
                console.log('error:', err);
                return;
            }
            console.log('success:', data);
        });
});

module.exports = oss;

**Comment by chylvina** [comment]
抱歉回晚了，代码没问题，请检查一下你的 key 和 secret

**Comment by chylvina** [comment]
key 和 secret 不能有空格。
