### ISSUE TITLE
OSS怎么设置HttpClient的超时？

### ISSUE THREAD

**Issue by jimtang9527** [aliyun-UED/aliyun-sdk-js#47]
在国内测试都还正常，不过把测试用例放在了travis-ci.org上，连接OSS就发现超时了。请问怎么设置OSS超时，谢谢

下面是错误信息
{ [NetworkingError: connect ETIMEDOUT 112.124.219.82:443]
  message: 'connect ETIMEDOUT 112.124.219.82:443',
  code: 'NetworkingError',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '112.124.219.82',
  port: 443,
  region: null,
  hostname: 'xxx.oss-cn-hangzhou.aliyuncs.com',
  retryable: true,
  time: Tue Dec 22 2015 08:42:16 GMT+0000 (UTC) }

**Comment by chylvina** [comment]
```javascript
var oss = new ALY.OSS({
  accessKeyId: "在阿里云OSS申请的 accessKeyId",
  secretAccessKey: "在阿里云OSS申请的 secretAccessKey",
  securityToken: "",
  endpoint: 'http://oss-cn-hangzhou.aliyuncs.com',
  timeout: 1000, // 毫秒为单位
  apiVersion: '2013-10-15'
});
```
