### ISSUE TITLE
InvalidStateError: DOM Exception 11 in old webkit browser

### ISSUE THREAD

**Issue by henrylilei** [aliyun-UED/aliyun-sdk-js#51]
I was testing our website using iOS 7 and encountered the following exception, InvalidStateError: DOM Exception 11.

After some digging, the culprit seems like this line, https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/lib/http/xhr.js#L27.

Based on the answer from http://stackoverflow.com/a/15623060/1361621 and bug report from Webkit https://bugs.webkit.org/show_bug.cgi?id=45994, I would suggest a change on the code by removing this line (https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/lib/http/xhr.js#L27). Any thoughts?

**Comment by chylvina** [comment]
fixed and closed, thanks for your feedback.
