### ISSUE TITLE
"rm -R" not available

### ISSUE THREAD

**Issue by TobiasNickel** [aliyun-UED/aliyun-sdk-js#52]
The api for OSS discribes deleteObject and deleteObjects. non of them can delete all files with a specific prefix.

I analyzed how the web on "oss.console.aliyun.com" is doing.
if uses a request to "delete_objects"

it has the following parameter:
bucketName: xxxx-xxxx
location: hangzhou
objects: 0000/sfd/
secToken:235hg5jkh32g45hj235kgj
token:Y9a064218746827134892150fac32e
collina:013#JxEAAgA ....

where "0000/sfd/" is the path or prefix to delete. 
but the sdk requires a param Delete that then has a list of Objects to specify the keys to delete.

how should I delete a delete a folder?

**Comment by chylvina** [comment]
sorry, I was very busy these days.

I can not answer your question, please file an work order on aliyun.com
