### ISSUE TITLE
STS sample code doesn't work

### ISSUE THREAD

**Issue by tiaozi0912** [aliyun-UED/aliyun-sdk-js#54]
The sample code here doesn't work https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/samples%2Fsts%2Ftest.js

Currently it only supports assumeRole method I think according to https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/apis%2Fsts-2015-04-01.json

Could you better document how to use STS in the SDK?

**Comment by chylvina** [comment]
sample updated. Thanks for your feedback.

for document pls refer to: https://help.aliyun.com/document_detail/ram/sts-api-reference/actions/assume_role.html
