### ISSUE TITLE
SLS构造protocol buffer数据报错

### ISSUE THREAD

**Issue by FFX313** [aliyun-UED/aliyun-sdk-js#56]
我使用示例的代码和示例数据发送Log：
`sls.putLogs({

    //必选字段

    projectName: projectName,

    logStoreName: logStoreName,

    logGroup: logGroup

}`

但是得到错误
no protos or msg exist!
check msg failed!
这个是pomelo-protobuf 的 encoder.js报出来的。
encoder.js在构造protos时使用的是：

//Get protos from protos map use the route as key

var protos = this.protos[route];

但是putLogs函数传递的键值是"logGroup"， sls.js里面proto_json的键值是"message LogGroup"。如果把"message LogGroup"改成"logGroup"就能工作了

**Comment by FFX313** [comment]
var pb = protoBufferEncode('LogGroup', logGroup);
这行代码传递的键值和数据模板的不匹配

**Comment by mayunlei** [comment]
已经修复了，请试一下
