### ISSUE TITLE
SignatureNonce太短导致十分容易碰撞

### ISSUE THREAD

**Issue by JasonGao180** [aliyun-UED/aliyun-sdk-js#61]
lib/service_interface/query.js:20:      SignatureNonce: Math.round(Math.random() * 1000000)
阿里云API禁止在一段时间之内发出两个SignatureNonce相同请求，而在这里SignatureNonce过短，只有六位数字范围，导致十分容易发生碰撞。

通常建议SignatureNonce使用UUID保证无法在短时间内发生碰撞；

**Comment by chylvina** [comment]
1.8.5 解决此问题，非常感谢你的反馈。
