### ISSUE TITLE
上传文件后返回是ETAG是什么鬼？

### ISSUE THREAD

**Issue by calidion** [aliyun-UED/aliyun-sdk-js#62]
{ ETag: '"9BEF661C19BD5C2D7639FB0DA0EE37C7"',
  RequestId: '56F124AF8C7624A57CED747D' }

我要的是文件名好不好？
或者至少说明出现了什么状况。
如果是文件重复
那也应该返回一个错误，说明文件重复。
返回ETag跟RequestId有什么意义？

**Comment by sugar-xj** [comment]
too young too naive

**Comment by calidion** [comment]
@sugar-xj 

没有用过aws的api吧？

看来aws在你的眼里young & naive?

拿面镜子照照自己。

**Comment by chylvina** [comment]
如果有需求请在阿里云网站提工单，谢谢两位的反馈 : )

**Comment by calidion** [comment]
如果服务器认为是重复，那么应该返回重复状态，并且给出来当前重复的文件名或者URL。
如果认为是错误，也要说明错误原因。
只有有了错误原因，才能有处理方案。现在返回个ETAG与RequestId本身没有问题。
但是是无意义的。
对于接口来说，要时刻注意，你这个接口是存储接口，不是HTTP服务器。

**Comment by JasonGao180** [comment]
1. 服务端不会生成文件名，文件名是在request里的，response里再放一次文件名没意义
2. ETag是文件的hash值；服务端返回 hash 值，是为了让client 端有能力确认服务端收到的文件是否和客户端发出的一致；

**Comment by calidion** [comment]
为什么成功会返回文件名？
狡辩无意义。谢谢。
有本事一直只返回ETAG跟RequestId.

**Comment by cesiya23** [comment]
@calidion 成功能返回文件名吗？
