### ISSUE TITLE
什么时候会实现移动推送的api呢

### ISSUE THREAD

**Issue by beesui** [aliyun-UED/aliyun-sdk-js#68]
如果没有人在实现，我来实现，然后PR吧

**Comment by chylvina** [comment]
推送有啊，push

**Comment by beesui** [comment]
lib/services/ 下面没有push的service，只在apis/push-2015-08-27.json 有一个api的描述

**Comment by beesui** [comment]
确实实现了，刚刚没看明白代码😂
