### ISSUE TITLE
没有短信服务的sample，难以使用

### ISSUE THREAD

**Issue by wuzhuzhu** [aliyun-UED/aliyun-sdk-js#93]
虽然已经支持了alidayu
https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/apis/dayu-2015-12-16.json

但是没有相应的import方法和具体使用用例
尝试过仿照其他sample的使用方法使用，都不可用。
还请给出实例，谢谢

**Comment by chylvina** [comment]
https://github.com/aliyun-UED/aliyun-sdk-js/blob/master/samples/dayu/test.js

**Comment by wuzhuzhu** [comment]
Many thanks
