### ISSUE TITLE
OTS文档找不到

### ISSUE THREAD

**Issue by puregardenia** [aliyun-UED/aliyun-sdk-js#94]
https://github.com/aliyun-UED/aliyun-sdk-js#目前支持的服务

OTS 文档 找不到了，求连接！

**Comment by yunlei** [comment]
OTS 改名叫Table Store了
https://help.aliyun.com/product/27278.html?spm=5176.750001.2.10.s2nMn3

**Comment by puregardenia** [comment]
@yunlei 但是这个好像没有nodejs 的sdk，有没有第三方推荐的

**Comment by chylvina** [comment]
在这里就是 ots，可以使用的。
